# Generated by Django 4.2.1 on 2023-07-03 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_remove_comments_likes_comments_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='likes',
        ),
    ]
